### ISSUE TITLE
Real FFT frequency axis to linear

### ISSUE THREAD

**Issue by javicordon** [fakufaku/esp32-fft#2]
I found your library after implementing one by myself.
You did a great job gathering most of the options into one library for benchmark in ESP32!
I believe you had configured your ESP32 clock at 160Mhz rather than 240Mhz. So real benchmark is a little faster than what you published.

In the other hand I am very interested in the Real FFT. I manage to use it but I don't know how to interpret the X axis of the FFT (Real data points -> FFT -> Frequency domain). When comparing it to traditional it seems like it is in a Log basis. Do you know how to interpret it/ convert it into a linear relationship?

I am currently using the 4096 size for data being sampled at 4096Hz. I know I have a frequency at 1500Hz which is being shown at 1095Hz. How can I get the output frequencies back to its linear approximation?

Thanks!
<img width="957" alt="esp32_fft" src="https://user-images.githubusercontent.com/32070981/51279530-590bc380-19bc-11e9-912a-b682ce773412.png">

**Comment by fakufaku** [comment]
Hi, thanks for pointing out the operating frequency of the ESP32. I had not considered that! :)

About the problem at hand, this is a little puzzling. The points in the buffer *should* be organized as explained in the README. Both input and output buffers are of size `NFFT` with the indexes organized as follows.
```
Input: [ x[0], x[1], x[2], ..., x[NFFT-1] ]
Output: [ X[0], X[NFFT/2], Re(X[1]), Im(X[1]), ..., Re(X[NFFT/2-1]), Im(X[NFFT/2-1]) ]
```
Note that both buffers contain `float` values. The output buffer contains real and imaginary parts interleaved, **except** for the first element (DC coeff) and center frequency. Both of these are real-values and stored in the first two elements of the buffer.

What might happen is that there is some shuffling of the elements in the array in the split radix algorithm that I have not considered. I have mostly tested if the reconstruction is exact which seems to be the case.

* Have you tried some of the other algorithms like radix-2 for example ?
* Would you share the code snippet that you used to produce the figure above ?

**Comment by javicordon** [comment]
Thanks for the fast reply.
I did consider the indexes as stated, also buffers size and type.

- It happens when using `USE_SPLIT_RADIX 1` and `USE_SPLIT_RADIX 0` also `LARGE_BASE_CASE 1` and `LARGE_BASE_CASE 0`, so I believe it is a shuffling problem but rather somewhere else.
- Sure, code snippet for printing out in Matlab just uploaded it to (https://github.com/javicordon/fft_print) format went weird when using 'insert code' from comments
- I may have a hint on where the issue may be, if I order the data input leaving one `0` between consecutive data points, I do get the desired output frequency response X. 
Such as:
`Input: [ x[0], 0, x[1], 0..., x[NFFT-1] ]`
Also works if 
`Input: [ 0, x[0], 0, x[1]..., x[NFFT-1] ]`
Either way I get
`Output: [ X[0], X[NFFT/2], Re(X[1]), Im(X[1]), ..., Re(X[NFFT/2-1]), Im(X[NFFT/2-1]) ]`

But if I use this I am only using half number of data inputs, which leaves me in the same situation as using FFT_COMPLEX with only Real values and Imaginary to zero. So performance would be about the same.

Could you point out where to find the mathematical algorithm for FFT Real, just for my understanding on how it works. I have implemented myself a radix-2 but it deals with Complex from the beginning.

**Comment by fakufaku** [comment]
There seems to be a few issues in the loops you use to read out the real/imag part of the data. Here is a loop that should work (not tested though).
```
// The array that contains the real part
printf("X_re = [ %f ", X[0]);  // DC coeff
for (int i = 2 ; i < NFFT ; i += 2)
  printf("%f ", X[i]);
printf("%f];", X[1]);  // Middle point

// The array that contains the imag part
printf("X_re = [ 0 ");  // DC coeff
for (int i = 3 ; i < NFFT ; i += 2)
  printf("%f ", X[i]);
printf("0];");  // Middle point

// The array that contains the squared magnitude
printf("X_sq = [ %f ", X[0] * X[0]);  // DC coeff
for (int i = 2 ; i < NFFT ; i += 2)
  printf("%f ", X[i] * X[i] + X[i+1] * X[i+1]);
printf("%f];", X[1] * X[1]);  // Middle point
```
One error I saw in the code that you sent is that `jump_x` should be 2 regardless of whether the input is real or complex (the output is always complex). In the case of audio data, the DC and middle coefficients can in general be ignored, so you could even ignore the first two elements of the output array (or set them to zero) to make your code simpler.

**Comment by fakufaku** [comment]
I could verify the code works. Here's my test code. I create a signal of length 64 as the sum of cosine and sine of frequency (discrete) `10` and `27`.  The flags are `USE_SPLIT_RADIX 1` and `LARGE_BASE_CASE 1`.
```
#include <stdio.h>
#include "fft.h"

void rfft64_test_print()
{
  // Sum of cosine of frequency 10 / 64 and sine of frequency 27 / 64
  // Expect the output to be X[10] == 32 and X[27] == -32, everything else being 0.
  float input[64] = {
    1.        ,  1.02696697, -1.21415304,  0.01439945, -1.63098631,
    0.82948361,  0.72878921,  0.54118494,  0.70710678, -1.78840995,
    0.05690575, -0.96810078,  1.08979021,  1.07880242, -0.1728868 ,
    0.32635103, -2.        ,  0.32635103, -0.1728868 ,  1.07880242,
    1.08979021, -0.96810078,  0.05690575, -1.78840995,  0.70710678,
    0.54118494,  0.72878921,  0.82948361, -1.63098631,  0.01439945,
    -1.21415304,  1.02696697,  1.        ,  0.0841735 ,  0.44878618,
    -1.97597001,  0.21677275, -0.43930296,  1.11896985,  1.12175429,
    -0.70710678,  0.12547072, -1.90466481,  0.57792013,  0.32442335,
    0.88276814,  0.93825367, -1.4374915 ,  0.        , -1.4374915 ,
    0.93825367,  0.88276814,  0.32442335,  0.57792013, -1.90466481,
    0.12547072, -0.70710678,  1.12175429,  1.11896985, -0.43930296,
    0.21677275, -1.97597001,  0.44878618,  0.0841735
  };
  float X[64];

  fft_config_t *fft_analysis = fft_init(64, FFT_REAL, FFT_FORWARD, input, X);
  fft_execute(fft_analysis);

  // The array that contains the real part
  printf("X_re = [ %f ", X[0]);  // DC coeff
  for (int i = 2 ; i < 64 ; i += 2)
    printf("%f ", X[i]);
  printf("%f];", X[1]);  // Middle point
  printf("\n");

  // The array that contains the imag part
  printf("X_im = [ 0 ");  // DC coeff
  for (int i = 3 ; i < 64 ; i += 2)
    printf("%f ", X[i]);
  printf("0];");  // Middle point
  printf("\n");

  // The array that contains the squared magnitude
  printf("X_sq = [ %f ", X[0] * X[0]);  // DC coeff
  for (int i = 2 ; i < 64 ; i += 2)
    printf("%f ", X[i] * X[i] + X[i+1] * X[i+1]);
  printf("%f];", X[1] * X[1]);  // Middle point
  printf("\n");

  fft_destroy(fft_analysis);

}

void app_main()
{
  while (1)
  {
    rfft64_test_print();
    vTaskDelay(10000 / portTICK_RATE_MS);
  }
}
```
Here is the python code I used to generate the input array and check the output of the FFT.
```
In [1]: N = 64

In [2]: n = np.arange(N)

In [3]: s1 = np.cos(2 * np.pi * 10 * n / N)

In [4]: s2 = np.sin(2 * np.pi * 27 * n / N)

In [5]: s = s1 + s2

In [6]: s
Out[6]:
array([ 1.        ,  1.02696697, -1.21415304,  0.01439945, -1.63098631,
        0.82948361,  0.72878921,  0.54118494,  0.70710678, -1.78840995,
        0.05690575, -0.96810078,  1.08979021,  1.07880242, -0.1728868 ,
        0.32635103, -2.        ,  0.32635103, -0.1728868 ,  1.07880242,
        1.08979021, -0.96810078,  0.05690575, -1.78840995,  0.70710678,
        0.54118494,  0.72878921,  0.82948361, -1.63098631,  0.01439945,
       -1.21415304,  1.02696697,  1.        ,  0.0841735 ,  0.44878618,
       -1.97597001,  0.21677275, -0.43930296,  1.11896985,  1.12175429,
       -0.70710678,  0.12547072, -1.90466481,  0.57792013,  0.32442335,
        0.88276814,  0.93825367, -1.4374915 ,  0.        , -1.4374915 ,
        0.93825367,  0.88276814,  0.32442335,  0.57792013, -1.90466481,
        0.12547072, -0.70710678,  1.12175429,  1.11896985, -0.43930296,
        0.21677275, -1.97597001,  0.44878618,  0.0841735 ])

In [7]: S = np.fft.rfft(s)

In [8]: S
Out[8]:
array([ 1.65978342e-14+0.00000000e+00j,  9.54962782e-15+1.05888995e-15j,
        2.26866317e-14+2.05067101e-14j,  1.56913005e-14-2.00672834e-15j,
       -1.23679890e-14+4.57815333e-14j, -3.01980663e-14-7.10542736e-15j,
        1.13344757e-14-3.39866210e-14j,  2.86402895e-14+1.38942990e-14j,
        1.14947874e-14+1.64049570e-14j, -1.85529240e-14+1.28405489e-14j,
        3.20000000e+01-1.95399252e-14j,  1.38905290e-14+3.03790221e-15j,
        1.88272139e-14+4.28143030e-14j, -1.43872606e-14-1.18041734e-14j,
       -3.40665116e-14+1.48860888e-14j, -7.07781543e-15-5.27102432e-14j,
        4.76285678e-14-2.20379270e-14j,  4.53951685e-14+2.46499850e-14j,
       -3.01493741e-15+2.39899176e-14j, -6.04084305e-15+1.48411792e-14j,
        7.90436922e-15+1.08859631e-14j, -2.78829873e-15+1.19196864e-14j,
        2.13162821e-14+2.13162821e-14j,  2.13796423e-15+3.79479302e-14j,
       -3.45874263e-14+5.96886055e-15j,  2.28577179e-14-5.22259341e-16j,
        3.39626237e-14+6.72657189e-14j, -1.98951966e-13-3.20000000e+01j,
       -1.52739416e-16-5.00956528e-14j,  6.06907074e-15-3.66456867e-14j,
        1.12861928e-14-1.21338468e-14j,  2.36313819e-14-3.39354519e-14j,
        1.95954364e-14+0.00000000e+00j])

In [9]: S[10]
Out[9]: (31.999999999999993-1.9539925233402755e-14j)

In [10]: S[27]
Out[10]: (-1.9895196601282805e-13-31.999999999999986j)
```

**Comment by fakufaku** [comment]
The real FFT algorithms can be implemented using complex FFTs of half size. The overall complexity is about half that of a complex FFT of the same size. I also wrote a blog post explaining the algorithms.
http://www.robinscheibler.org/2013/02/13/real-fft.html

**Comment by javicordon** [comment]
- I noticed after you pointed out that the printing function I shared was not the working version, sorry.
- You made me realize where my error was, I was printing `fft_analysis ` output, after having executed `fft_synthesis `. Where `fft_synthesis ` input was `fft_analysis ` output, therefore destroying it. It was an error of timing accessing the data. 

Thank you very much for all the answers with examples and time.  Will read your blog there are quite a few interesting subjects.
ありがとうございました

**Comment by fakufaku** [comment]
Great! Glad it worked out in the end :)

**Comment by Gabriel-Gardin** [comment]
Hello, I'm having the same problem while trying to decompose an analog signal to frequency domain.  I'm currently using parts of the sample code and sampling an sinusoidal signal from a function generator with the in-built adc of the esp32... I can see that it works, since it's responding to the frequency change, but I cannot get the right values... 

I've sampled the data using a for loop and print the result with your code:
`
  // The array that contains the real part
  printf("X_re = [ %f ", X[0]);  // DC coeff
  for (int i = 2 ; i < 64 ; i += 2)
    printf("%f ", X[i]);
  printf("%f];", X[1]);  // Middle point
  printf("\n");`

**Comment by Gabriel-Gardin** [comment]
Another question, is the frequency limited by the size of the buffer?

**Comment by fakufaku** [comment]
@Gabriel-Gardin About your first question, it is difficult to answer without extra information. Please post code and detailed explanation of what the problem is. If the problem is really the same, have you considered the solution found by @javicordon ?

> You made me realize where my error was, I was printing fft_analysis output, after having executed fft_synthesis . Where fft_synthesis input was fft_analysis output, therefore destroying it. It was an error of timing accessing the data.

About the second question, the frequency is not limited by the buffer size, but the resolution in frequency is. With a buffer length of 64, one FFT bin has width `f_s / 64` (`f_s` is the sampling frequency). So if `f_s = 16000 Hz`, then one FFT bin is `250 Hz` wide.

**Comment by ElianVivas** [comment]
Hi, I am new to ESP32 and ESP-idf. I found your library after much searching. I am interested in applying the fft to analyze vibrations in an electric motor. My problem is the following. I create a new project in idf with the Sample_project template, then I include the fft-master folder in "Add your ESP-IDF Component directory" when including the library it is loaded correctly, however when building the project I get the following error:

FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj 
C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/newlib/platform_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/port/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/private_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/heap/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/log/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps/sntp -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/lwip/src/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include/arch -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/. -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/hal/platform_port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_common/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/soc -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/public_compat -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/xtensa/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/driver/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_pm/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ringbuf/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/efuse/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/vfs/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_wifi/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_event/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_netif/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_eth/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/tcpip_adapter/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/esp32/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_ipc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/app_trace/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_timer/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/mbedtls/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/esp_crt_bundle/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/app_update/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/bootloader_support/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/nvs_flash/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/pthread/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/xtensa -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/espcoredump/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/espcoredump/include/port/xtensa -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/esp_supplicant/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/ieee802154/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/console -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/asio/asio/asio/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/asio/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/cbor/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/unity/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/unity/unity/src -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/cmock/CMock/src -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/coap/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/coap/libcoap/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/nghttp/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/nghttp/nghttp2/lib/includes -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp-tls -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp-tls/esp-tls-crypto -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_adc_cal/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_hid/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/tcp_transport/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_http_client/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_http_server/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_https_ota/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_lcd/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_lcd/interface -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/protobuf-c/protobuf-c -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/common -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/security -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/transports -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/mdns/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_local_ctrl/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/sdmmc/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_serial_slave_link/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/esp_websocket_client/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/expat/expat/expat/lib -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/expat/port/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/wear_levelling/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/fatfs/diskio -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/fatfs/vfs -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/fatfs/src -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/freemodbus/common/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/idf_test/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/idf_test/include/esp32 -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/jsmn/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/json/cJSON -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/libsodium/libsodium/src/libsodium/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/libsodium/port_include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/mqtt/esp-mqtt/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/openssl/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/perfmon/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/spiffs/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/ulp/include -IC:/Espressif/frameworks/esp-idf-v4.4.1/components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Users/Usuario/fft_fakufaku=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4.1=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"GIT-NOTFOUND\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c ../main/main.c
../main/main.c:2:10: fatal error: fft.h: No such file or directory
 #include "fft.h"
          ^~~~~~~
compilation terminated.
[6/57] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\Users\Usuario\fft_fakufaku\build\bootloader\esp-idf\esptool_py && C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v4.4.1/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/Users/Usuario/fft_fakufaku/build/bootloader/bootloader.bin"
Bootloader binary size 0x62c0 bytes. 0xd40 bytes (12%) free.
ninja: build stopped: subcommand failed.

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1. 


any idea what could be the error?

**Comment by fakufaku** [comment]
@ElianVivas Hello, this seems to be related to the use of ESP-IDF. I have not been using ESP-IDF for some time and I am not up-to-date on the latest details. It is best to check the ESP-IDF documentation first for details on how to include libraries. If the error persists and you think this is related specifically to the FFT library, please open a new issue. Sorry I am not able to help more.
