### ISSUE TITLE
HW suggestion

### ISSUE THREAD

**Issue by MrJBSwe** [fakufaku/esp32-fft#3]
This might be of interest
https://github.com/kendryte/kendryte-standalone-demo/tree/master/fft_test

FFT_N       512  16bit  HW 22us SW 2300us

http://blog.sipeed.com/p/182.html

https://www.seeedstudio.com/Sipeed-M1-dock-suit-M1-dock-2-4-inch-LCD-OV2640-K210-Dev-Board-1st-RV64-AI-board-for-Edge-Computing-p-3211.html

**Comment by fakufaku** [comment]
Thanks for the suggestion. Does this chip has a hardware fft module ? That is pretty cool. Do you have a reference to the chip itself ?

**Comment by MrJBSwe** [comment]
>hardware fft module ?

yes that's my understanding " It have APU(Audio Processor),  support 8mics, up to 192KHz sample rate, hardcore FFT unit inside"
I measured 22us running the test sample code

>reference to the chip itself

https://kendryte.com/downloads/

KPU K210 features:

Dual-core RISC-V 64bit IMAFDC,  on-chip huge 8MB high-speed SRAM 400MHz frequency
 KPU(Neural Network Processor) inside
 APU(Audio Processor),  support 8mics, upto 192KHz sample rate, hardcore FFT unit inside
 FPIOA(Field Programmable IO Array), you can map 255 functions to all 48 GPIOs on the chip.
 DVP camera and MCU LCD interface,
 AES Accelerator, SHA256 Accelerator, FFT Accelerator(not APU's one), OTP, UART,WDT,IIC,SPI,I2S,TIMER,RTC,PWM, etc.

https://www.indiegogo.com/projects/sipeed-maix-the-world-first-risc-v-64-ai-module/x/19789803#/
