### ISSUE TITLE
Slightly unexpected results, maybe my mistake?

### ISSUE THREAD

**Issue by MonoAnji** [fakufaku/esp32-fft#8]
For some reason if I generate a sine wave at excactly 1000.f Hz and 32kHz sample rate and run it through the real fft, I'll yield a peak frequency of exactly 3000 Hz, which is a bit odd, since it's not just a multiple fundamental, the fundamental has a much lower rms value, all the multiples have a quite low assigned value, and everything else is 0. I wonder why that is, because dumping the exact same sine wave as pcm wav file and running it through e.g. Audacity yields a perfect peak at 1000 with no harmonics. Size of fft doesn't matter, 2 << 8 through 2 << 16 all yield the exact same result.

Interestingly just using 1000.1f  will work just fine and be "seen" as around 1000-ish.

**Comment by fakufaku** [comment]
Hi @MonoAnji hard to diagonse what's going on here without code for how you generate the sine wave, run the FFT and compute the frequency indices.
If you have a minimal example that you'd like to share I could take a look. Or do you have a graph of the output from the real FFT ?

**Comment by MonoAnji** [comment]
```
//fyi: _samples_per_period = SAMPLE_RATE / frequency;
//      typedef float value_t;
value_t Sine::calculateValue(unsigned int position) {
	return sin(position * M_TWOPI / _samples_per_period);
}
void test_quality_small_online_version() {
	Oscillator *sine = new Sine(1000.f, 1.f);
	int k, n;

	for (n = 8 ; n <= 16 ; n++) {
		int NFFT = 1 << n;
		fft_config_t *fft_analysis = fft_init(NFFT, FFT_REAL, FFT_FORWARD, nullptr, nullptr);

		int size = fft_analysis->size;

		for (k = 0 ; k < size; k++) {
			fft_analysis->input[k] = sine->calculateValue(k);
		}

		fft_execute(fft_analysis);

		float fundamental_peak = 0.f;
		float fundamental_peak_calc = 0.f;
		for (k = 0 ; k < size; k+=2) {
			float re = fft_analysis->output[k];
			float im = fft_analysis->output[k];

			if (k > 2) {
				float freq = (float)k/2.f * (float)SAMPLE_RATE/(float)size;
				float amp = sqrtf(powf(re, 2.)+powf(im, 2.));
				float hint = re * im;
				if (hint > fundamental_peak_calc) {
					fundamental_peak = freq;
					fundamental_peak_calc = hint;
				}
			}
		}
		printf("Fundamental [n=%2d]: Method 1 -> %f\n", n, fundamental_peak);
	}
}
```

I tried to exact the main thing that's going on here, sorry for my weird coding style, I'm not usually a c(++) programmer. The sine calculation is usually in it's own class, but for a quick look this should do it. :) 
Thank you!

**Comment by MonoAnji** [comment]
![Annotation 2020-03-18 100532](https://user-images.githubusercontent.com/16881074/76943750-259a3100-6900-11ea-9120-bc9b4c0b3df2.png)

**Comment by fakufaku** [comment]
Hi @MonoAnji ,

I am not completely sure, but I found the following. In the next two following lines, you are not picking up the imaginary part of the complex number, but the real part twice:
```
float re = fft_analysis->output[k];
float im = fft_analysis->output[k];
```
The second line should be
```
float im = fft_analysis->output[k];
```
Then, looking at the figure you uploaded, the magnitudes are too small.
In fact, the peak should be exactly `NFFT / 2` tall, unless you apply some scaling.

In addition, the FFT of a sine wave does not have any real component. So I believe that the graph only contains some numerical errors of the real part that should be uniformly zero. The magnitudes are consistent with round-off errors for float single precision.

Here is a test signal that I generated
```
x = [0.000, 0.383, 0.707, 0.924, 1.000, 0.924, 0.707, 0.383, 0.000, -0.383, -0.707, -0.924, -1.000, -0.924, -0.707, -0.383]
```
This is just the sine of frequency 1 and period 16 samples. If you run a real FFT of length 16 on this, you should get the following output up to some small numerical errors (in the format provided by the FFT library).
```
y = [0, 0, 0, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by MonoAnji** [comment]
Your're so very right, gaah... I'm stupid. どもうありがとうございます！
I totally should have seen this. I guess I still havae a bit of a problem understanding how fft works exactly und how to interpret the numbers. Sorry.
I hope it's ok if I use your library in a little project of mine? I'm trying to build a wierd-ish bass pedal centered around an esp32.

**Comment by fakufaku** [comment]
@MonoAnji No worries! This kind of mistakes happen all the time! 😄 
And, by any means, please do use this library in your projects! Have fun!
